version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - techcard_network

  techcard-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: techcard-master
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    networks:
      - techcard_network

networks:
  techcard_network:

volumes:
  mongodb_data:
    driver: local
